version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 9000:9000
    networks:
      - kafkanet

  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - 2181:2181
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ZOOKEEPER_CONNECTION_TIMEOUT_MS=180000
      - KAFKA_CREATE_TOPICS=iexfinance:1:1
    networks:
      - kafkanet

networks:
  kafkanet:
    driver: bridge
