version: '2'
services:
  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9095:9094"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      # KAFKA_CREATE_TOPICS: iexfinance-1:1:2,iexfinance-2:1:2,iexfinance-3:1:2
      # KAFKA_CREATE_TOPICS: iexfinance-1:1:1

      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9095,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://localhost:9095,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_PORT: 9094

      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181

  # kafka2:
  #   image: wurstmeister/kafka
  #   depends_on:
  #     - zoo1
  #     - zoo2
  #     - zoo3
  #   ports:
  #     - "9094:9092"
  #   environment:
  #     KAFKA_LOG_DIRS: /kafka
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,OUTSIDE://localhost:9092
  #     KAFKA_LISTENERS: INSIDE://localhost:9094,OUTSIDE://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_LOG_RETENTION_HOURS: "168"
  #     KAFKA_LOG_RETENTION_BYTES: "100000000"
  #     KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181
  #
  # kafka3:
  #   image: wurstmeister/kafka
  #   depends_on:
  #     - zoo1
  #     - zoo2
  #     - zoo3
  #   ports:
  #     - "9095:9092"
  #   environment:
  #     KAFKA_LOG_DIRS: /kafka
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9095,OUTSIDE://localhost:9092
  #     KAFKA_LISTENERS: INSIDE://localhost:9095,OUTSIDE://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_LOG_RETENTION_HOURS: "168"
  #     KAFKA_LOG_RETENTION_BYTES: "100000000"
  #     KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181

  zoo1:
    image: wurstmeister/zookeeper
    environment:
      MYID: 1
      SERVERS: zoo1,zoo2,zoo3
    ports:
      - "2181:2181"
      - "2888"
      - "3888"

  zoo2:
    image: wurstmeister/zookeeper
    environment:
      MYID: 2
      SERVERS: zoo1,zoo2,zoo3
    ports:
      - "2182:2181"
      - "2888"
      - "3888"

  zoo3:
    image: wurstmeister/zookeeper
    environment:
      MYID: 3
      SERVERS: zoo1,zoo2,zoo3
    ports:
      - "2183:2181"
      - "2888"
      - "3888"
